spring:
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path= /api/customer-service/**
        
      - id: CATTLE-SERVICE
        uri: lb://CATTLE-SERVICE
        predicates:
        - Path= /api/cattle-service/**
          
  application:
    name: Api-Gateway

server:
  port: 9191