spring:
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path= /api/customer-service/**
        
      - id: CATTLE-SERVICE
        uri: lb://CATTLE-SERVICE
        predicates:
        - Path= /api/cattle-service/**
          
  application:
    name: Api-Gateway

#server:
#  port: 9191 

security:
  user:
    password: ${eureka.password}
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://doctor-cattle-parent.herokuapp.com}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:API_GATEWAY}
  password: ${USER_PASSWORD:password}
   #http://localhost:8761/eureka
     
  